name: element
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.18.1
  - opencv=4.1.0
  - pip=20.0.2
  - python=3.6.10
  - pip:
    - imageio==2.8.0
    - imgaug==0.4.0
    - pillow==7.0.0
    - portalocker==1.5.2
    - sqlalchemy==1.3.19
    - psycopg2==2.8.5
    - pynng==0.4.0


